// <auto-generated />
namespace Taharifran.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class FriendRequests : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FriendRequests));
        
        string IMigrationMetadata.Id
        {
            get { return "201901120934070_FriendRequests"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
